[pytest]
pythonpath = src
testpaths = tests
filterwarnings =
    ignore:X does not have valid feature names:UserWarning
    ignore:The 'generic' unit for NumPy timedelta is deprecated:DeprecationWarning
